Add sniyaz iros19 surgical paper.
personalrobotics/pubs pull request #38
Opened 2019-08-01 05:33 UTC by sniyaz

- [ ] Update `.bib` file
- [ ] Upload publication PDF to [Google Drive](https://drive.google.com/drive/folders/1M9fOGIIQ3e1R62dtVit5rZ5iWZqxfWV9)

2019-08-01 05:42 UTC, brianhou requested changes

2019-08-01 05:42 UTC, brianhou commented on siddpubs-conf.bib
> +	}
Indentation needs to be consistent with other entries.

2019-08-02 04:27 UTC, sniyaz commented
Sorry, fixed indentation.

2019-08-02 05:15 UTC, brianhou approved these changes

2019-08-02 05:15 UTC, merged