Add the 2021 icra entry
personalrobotics/pubs pull request #60
Opened 2021-05-07 18:39 UTC by Kelym

- [x] Update `.bib` file
- [x] Upload publication PDF to [Google Drive](https://drive.google.com/drive/folders/1M9fOGIIQ3e1R62dtVit5rZ5iWZqxfWV9)

2021-05-07 18:42 UTC, brianhou requested changes

2021-05-07 18:42 UTC, brianhou commented on siddpubs-conf.bib
> + author = {Ke, L., Wang, J., Bhattacharjee, T., Boots, B. and Srinivasa, S.S.},
Use `and` to separate authors.

2021-05-07 18:42 UTC, egordon requested changes

2021-05-07 18:42 UTC, egordon commented on siddpubs-conf.bib
> + author = {Ke, L., Wang, J., Bhattacharjee, T., Boots, B. and Srinivasa, S.S.},
I think the website assumes that authors are separated by ` and `, see all other entries below.

Best to keep that consistent

2022-03-21 18:21 UTC, egordon commented
@Kelym Noticed this has been tied up for a year. Mind fixing the issues?

2022-03-31 21:01 UTC, Kelym commented
@egordon @brianhou 
Fixed the "and". Ready to merge now.

2022-03-31 21:18 UTC, brianhou approved these changes

2022-03-31 21:18 UTC, merged